
substitutions:
  sp1_current_resistor: "0.00221"
  sp1_voltage_divider: "820"   #"871"
  #############
  # Note: These numbers were found online
  # BW SHP2 Current Resistor: 0.0028
  # BW SHP2 Voltage Devider: 960
  # Gosund SP1 Current Resistor: 0.00221
  # Gosund SP1 Voltage Devider: 871
  # Gosund SP1 Current Resistor ALT: 0.00103
  # Gosund SP1 Voltage Devider ALT: 2160
  #############
  red_led_pin: GPIO13
  blue_led_pin: GPIO1

board:
esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min


esphome:
  name: esphome-web-003c17
  friendly_name: ESPHome Web 003c17
  min_version: 2025.5.0
  name_add_mac_suffix: false
  on_boot:
    - priority: 90
      then:
      # Make sure the relay is in a known state at startup
      - switch.turn_off: relay
      # Default to Power ON the switch relay
      - delay: 20s
      - switch.turn_on: relay


# Enable Home Assistant API
api:
  encryption:
    key: " xxx "

ota:
  - platform: esphome
    password: " xx "

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gosund SP1 Fallback Hotspot"
    password: " xxx "

logger:
  level: DEBUG

captive_portal:
  
sensor:
  # Gosund SP1 Config
  # Power sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${sp1_current_resistor}
    voltage_divider: ${sp1_voltage_divider}
    change_mode_every: 8
    update_interval: 5s
    # Current sensor
    current:
      name: Amperes
      unit_of_measurement: A
      accuracy_decimals: 2
    # Voltage sensor
    voltage:
      name: Volts
      unit_of_measurement: V
      accuracy_decimals: 0
    # Power sensor
    power:
      id: power
      name: Watts
      unit_of_measurement: W
      accuracy_decimals: 0
  # Total daily energy sensor
  - platform: total_daily_energy
    name: KWh
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
# Binary sensor for the power button
binary_sensor:
  - platform: gpio
    name: Botao
    id: botaoonoff
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: relay
    internal: False

switch:
  # Switch for the relay
  - platform: gpio
    id: relay
    name: Power
    icon: mdi:water-boiler
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led 

output:
  # esphome state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: ${blue_led_pin}
      inverted: true

light:
  # Power state light
  - platform: monochromatic
    output: state_led
    id: led

# Uses the red LED as a status indicator
status_led:
  pin:
    number: ${red_led_pin}
    inverted: true
    
    
